language: node_js
node_js:
  - "node"
  - "7"

before_install:
  - npm install -g node-gyp
  - cd backend/src

install:
  - npm install


before_script:
  - npm install -g gulp



script:
  - npm test


env:
  - CXX=g++-5


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5